### ISSUE TITLE
Error when running Accessibility Area from point file

### ISSUE THREAD

**Issue by baswein** [nilsnolde/OSMtools#44]
Hello, 
I love the plugin. However when I try to run it from a point file containing 7 points for a distance on .4 km. 
I get this error:
2018-02-15T15:17:49	1	Traceback (most recent call last):
			  File "C:/Users/BG/.qgis2/python/plugins\OSMtools\osm_tools.py", line 262, in run
			    self.access_anal.iterAnalysis()
			  File "C:/Users/BG/.qgis2/python/plugins\OSMtools\osm_tools_access.py", line 382, in iterAnalysis
			    feat_list, isochrone_list = self.accRequest(feat_in_list)
			  File "C:/Users/BG/.qgis2/python/plugins\OSMtools\osm_tools_access.py", line 165, in accRequest
			    root = json.loads(response.text)
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\json\__init__.py", line 338, in loads
			    return _default_decoder.decode(s)
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\json\decoder.py", line 365, in decode
			    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\json\decoder.py", line 383, in raw_decode
			    raise ValueError("No JSON object could be decoded")
			ValueError: No JSON object could be decoded
Any ideas? 
And thanks.

**Comment by nilsnolde** [comment]
This is a server error. It likely means that one coordinate can not be processed, bcs it's not close to a road. Check your input coordinates.

The plugin is set to deprecated since a few days, I'm currently refactoring the whole thing to QGIS v3, release next week. From Friday on, you'll hopefully have a working plugin in QGIS3.

**Comment by nilsnolde** [comment]
Branch qgis299-dev has a working plugin vor QGIS2.99. Please try again that version.

**Comment by baswein** [comment]
Thanks! I'll try it out.
