### ISSUE TITLE
Routing Error OSM tools

### ISSUE THREAD

**Issue by COMMUTERMEXICO** [nilsnolde/OSMtools#55]
Hi Nils!!! Greetings from Mexico!

I´m using the OSM TOOLS  plugin in QGIS and I want to calculate the routes between a layer whith 125 origins and a layer with 125 destinations (both layers are points and the fields are: id, lat, long) but when  I run the task it appears the next warning: 

"IndexError: list index out of range 
Traceback (most recent call last):
  File "C:/Users/josue.gonzalez/.qgis2/python/plugins\OSMtools\osm_tools.py", line 144, in run
    route.directions_calc()
  File "C:/Users/josue.gonzalez/.qgis2/python/plugins\OSMtools\directions.py", line 137, in directions_calc
    layer_out = self._addLine(responses, values_list)
  File "C:/Users/josue.gonzalez/.qgis2/python/plugins\OSMtools\directions.py", line 183, in _addLine
    values_list[i][0],
IndexError: list index out of range"

How can I solve this?  Thank you very much!!!

Baruc

**Comment by temospena** [comment]
Hi. Thanks so much for this app!
I'm having the same issue... 
It works fine for driving -shortest, but when I select driving- fastest it shows tis error:

> Traceback (most recent call last):
			  File "C:/Users/rosa7/.qgis2/python/plugins\OSMtools\osm_tools.py", line 144, in run
			    route.directions_calc()
			  File "C:/Users/rosa7/.qgis2/python/plugins\OSMtools\directions.py", line 88, in directions_calc
			    route_dict = self._selectInput()
			  File "C:/Users/rosa7/.qgis2/python/plugins\OSMtools\directions.py", line 205, in _selectInput
			    layer = [layer for layer in self.iface.mapCanvas().layers() if layer.name() == layer_name][0]
			IndexError: list index out of range

**Comment by westdun** [comment]
Hi Nils. I had the same issue and the workaround in #47 worked perfectly
